name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Project
      run: |
        composer install
        composer ssg

    - name: Checkout GitHub Pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: build